#!/usr/bin/env python3
"""Usage: build the PL154 alphabetical payload and helper request.

Run from the repository root:
  python scripts/pipeline_index_extraction/build_pl154_alphabetical_payload.py \
    --write-helper-request \
    --helper-request-json /homessddata/Projects/pdfocr/data/alphabetical_index_payloads/PL154_helper_request.json

  python scripts/index_target_locator.py \
    --input /homessddata/Projects/pdfocr/data/alphabetical_index_payloads/PL154_helper_request.json \
    --output /homessddata/Projects/pdfocr/data/alphabetical_index_payloads/PL154_helper_output.json \
    --pretty

  python scripts/pipeline_index_extraction/build_pl154_alphabetical_payload.py \
    --build-payload \
    --helper-output-json /homessddata/Projects/pdfocr/data/alphabetical_index_payloads/PL154_helper_output.json \
    --intermediate-dir /homessddata/Projects/pdfocr/data/intermediate_payloads/PL154 \
    --output-file /homessddata/Projects/pdfocr/data/alphabetical_index_payloads/PL154_alphabetical_indices.json
"""

from __future__ import annotations

import argparse
import json
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path("/homessddata/Projects/pdfocr")
VOLUME_ID = "PL154"
COLLECTION = "PL"
VOLUME_LABEL = "PL154"
SOURCE_ROOT = ROOT / "teste/PL154/text"
SECTION1_FILE = SOURCE_ROOT / "3b651b79-9fc4-4a87-a056-9723294703d9-008.txt"
SECTION2_FILE = SOURCE_ROOT / "5fb219ee-e77f-4c60-84fa-b4db736c0c56-732.txt"
SCRIPT_TARGET_LOCATOR = ROOT / "scripts/index_target_locator.py"

SECTION_1_KEY = f"{VOLUME_ID}:alpha:author_index:001"
SECTION_2_KEY = f"{VOLUME_ID}:alpha:ordo_rerum:002"

SECTION1_HEADING = "ELENCHUS AUCTORUM ET OPERUM QUI IN HOC TOMO CLIV CONTINENTUR."
SECTION2_HEADING = "ORDO RERUM QUÆ IN HOC TOMO CONTINENTUR."


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def read_json(path: Path, default: Any | None = None) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def strip_accents(text: str) -> str:
    value = unicodedata.normalize("NFKD", text.replace("\xa0", " "))
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    value = value.replace("Æ", "AE").replace("æ", "ae").replace("Œ", "OE").replace("œ", "oe")
    return value


def normalize(text: str | None) -> str | None:
    if text is None:
        return None
    value = strip_accents(text)
    value = re.sub(r"\s+", " ", value).strip(" ,;:.")
    return value or None


def sort_norm(text: str | None) -> str | None:
    value = normalize(text)
    return value.lower() if value else None


HELPER_ROWS: list[dict[str, Any]] = [
    # Section 1: ELENCHUS
    {
        "entry_id": "pl154_elenchus_chronicon_017",
        "lemma_raw": "Chronicon",
        "query_names": [
            "Chronicon",
            "Hugonis chronicon",
            "CHRONICON. — PROOEMIUM.",
            "Hugonis chronicon.",
        ],
        "page_hints": ["17"],
        "page_hint_ints": [17],
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nChronicon. Col. 17.",
    },
    {
        "entry_id": "pl154_elenchus_opusculum_433",
        "lemma_raw": "Opusculum de sacramento altaris",
        "query_names": [
            "Opusculum de sacramento altaris",
            "B. Wolphelmus",
            "sacramento altaris",
        ],
        "page_hints": ["433"],
        "page_hint_ints": [433],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS.\nOpusculum de sacramento altaris. 433.",
    },
    {
        "entry_id": "pl154_elenchus_versus_433",
        "lemma_raw": "Versus de utroque testamento",
        "query_names": [
            "Versus de utroque testamento",
            "utroque testamento",
            "B. Wolphelmus",
        ],
        "page_hints": ["433"],
        "page_hint_ints": [433],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS.\nVersus de utroque testamento. 433.",
    },
    {
        "entry_id": "pl154_elenchus_chronica_459",
        "lemma_raw": "Chronica",
        "query_names": [
            "Chronica",
            "EKKEHARDUS URAUGIENSIS",
            "Chronicon Wirziburgensr.",
        ],
        "page_hints": ["459"],
        "page_hint_ints": [459],
        "context_raw": "EKKEHARDUS URAUGIENSIS.\nChronica. 459.",
    },
    {
        "entry_id": "pl154_elenchus_gesta_treverorum_1064",
        "lemma_raw": "Gesta Treverorum",
        "query_names": [
            "Gesta Treverorum",
            "ANONYMUS",
            "Treverorum",
        ],
        "page_hints": ["1064"],
        "page_hint_ints": [1064],
        "context_raw": "ANONYMUS.\nGesta Treverorum. 1064.",
    },
    {
        "entry_id": "pl154_elenchus_chronicon_huberti_1337",
        "lemma_raw": "Chronicon S. Huberti Andaginensis",
        "query_names": [
            "Chronicon S. Huberti Andaginensis",
            "Andaginensis",
            "HUBERTI",
        ],
        "page_hints": ["1337"],
        "page_hint_ints": [1337],
        "context_raw": "ANONYMUS.\nChronicon S. Huberti Andaginensis. 1337.",
    },
    # Section 2: ORDO RERUM
    {
        "entry_id": "pl154_ordo_chronicon_009",
        "lemma_raw": "CHRONICON",
        "query_names": [
            "HUGO ABBAS FLAVINIACENSIS",
            "CHRONICON",
            "CHRONICON. 9",
        ],
        "page_hints": ["9"],
        "page_hint_ints": [9],
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nCHRONICON. 9.",
    },
    {
        "entry_id": "pl154_ordo_necrologium_019",
        "lemma_raw": "Necrologium",
        "query_names": [
            "Necrologium",
            "Hugo Abbas Flaviniacensis",
            "Necrologium. 19",
        ],
        "page_hints": ["19"],
        "page_hint_ints": [19],
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nNecrologium. 19.",
    },
    {
        "entry_id": "pl154_ordo_libri_primus_021",
        "lemma_raw": "Libri primus",
        "query_names": [
            "Libri primus",
            "Hugo Abbas Flaviniacensis",
            "Libri primus. 21",
        ],
        "page_hints": ["21"],
        "page_hint_ints": [21],
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nLibri primus. 21.",
    },
    {
        "entry_id": "pl154_ordo_libri_secundus_197",
        "lemma_raw": "Libri secundus",
        "query_names": [
            "Libri secundus",
            "Hugo Abbas Flaviniacensis",
            "Libri secundus. 197",
        ],
        "page_hints": ["197"],
        "page_hint_ints": [197],
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nLibri secundus. 197.",
    },
    {
        "entry_id": "pl154_ordo_vita_wolphelmi_403",
        "lemma_raw": "Vita B. Wolphelmi",
        "query_names": [
            "Vita B. Wolphelmi",
            "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM",
            "Wolphelmi",
        ],
        "page_hints": ["403"],
        "page_hint_ints": [403],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nVita B. Wolphelmi. 403.",
    },
    {
        "entry_id": "pl154_ordo_observationes_403",
        "lemma_raw": "Observationes præviæ",
        "query_names": [
            "Observationes præviæ",
            "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM",
            "præviæ",
        ],
        "page_hints": ["403"],
        "page_hint_ints": [403],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nObservationes præviæ. 403.",
    },
    {
        "entry_id": "pl154_ordo_prologus_405",
        "lemma_raw": "Prologus",
        "query_names": [
            "Prologus",
            "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM",
            "Prologus. 405",
        ],
        "page_hints": ["405"],
        "page_hint_ints": [405],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nPrologus. 405.",
    },
    {
        "entry_id": "pl154_ordo_jocipht_407",
        "lemma_raw": "Jocipht vita",
        "query_names": [
            "Jocipht vita",
            "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM",
            "Jocipht",
        ],
        "page_hints": ["407"],
        "page_hint_ints": [407],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nJocipht vita. 407.",
    },
    {
        "entry_id": "pl154_ordo_opusculum_433",
        "lemma_raw": "Opusculum de Sacramento Altaris",
        "query_names": [
            "Opusculum de Sacramento Altaris",
            "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM",
            "Sacramento Altaris",
        ],
        "page_hints": ["433"],
        "page_hint_ints": [433],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nOpusculum de Sacramento Altaris. 433.",
    },
    {
        "entry_id": "pl154_ordo_versus_433",
        "lemma_raw": "Versus de utroque Testamento",
        "query_names": [
            "Versus de utroque Testamento",
            "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM",
            "utroque Testamento",
        ],
        "page_hints": ["433"],
        "page_hint_ints": [433],
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nVersus de utroque Testamento. ibid.",
    },
    {
        "entry_id": "pl154_ordo_chronica_433",
        "lemma_raw": "Chronica",
        "query_names": [
            "Chronica",
            "EKKEHARDUS URAUIGIENSIS",
            "Chronica. ibid.",
        ],
        "page_hints": ["433"],
        "page_hint_ints": [433],
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nChronica. ibid.",
    },
    {
        "entry_id": "pl154_ordo_perutil_prefatio",
        "lemma_raw": "Perutil præfatio",
        "query_names": [
            "Perutil præfatio",
            "EKKEHARDUS URAUIGIENSIS",
            "præfatio",
        ],
        "page_hints": [],
        "page_hint_ints": [],
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nPerutil præfatio.",
    },
    {
        "entry_id": "pl154_ordo_waitz_453",
        "lemma_raw": "V. Cl. G. Waitz proœmium",
        "query_names": [
            "V. Cl. G. Waitz proœmium",
            "Waitz proœmium",
            "EKKEHARDUS URAUIGIENSIS",
        ],
        "page_hints": ["453"],
        "page_hint_ints": [453],
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nV. Cl. G. Waitz proœmium. 453.",
    },
    {
        "entry_id": "pl154_ordo_wirziburgensr_459",
        "lemma_raw": "CHRONICON WIRZIBURGENSR",
        "query_names": [
            "CHRONICON WIRZIBURGENSR",
            "Wirziburgensr",
            "EKKEHARDUS URAUIGIENSIS",
        ],
        "page_hints": ["459"],
        "page_hint_ints": [459],
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nCHRONICON WIRZIBURGENSR. 459.",
    },
    {
        "entry_id": "pl154_ordo_epylion_497",
        "lemma_raw": "Epylion (id est abbreviatio) Eusebii de sequenti opere",
        "query_names": [
            "Epylion (id est abbreviatio) Eusebii de sequenti opere",
            "Eusebii",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["497"],
        "page_hint_ints": [497],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nEpylion (id est abbreviatio) Eusebii de sequenti opere. 497.",
    },
    {
        "entry_id": "pl154_ordo_excerptum_563",
        "lemma_raw": "Excerptum de Vita Alexandri Magni",
        "query_names": [
            "Excerptum de Vita Alexandri Magni",
            "Alexandri Magni",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["563"],
        "page_hint_ints": [563],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nExcerptum de Vita Alexandri Magni. 563.",
    },
    {
        "entry_id": "pl154_ordo_orig_franconum_713",
        "lemma_raw": "De origine Franconum",
        "query_names": [
            "De origine Franconum",
            "Franconum",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["713"],
        "page_hint_ints": [713],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe origine Franconum. 713.",
    },
    {
        "entry_id": "pl154_ordo_historia_gothorum_743",
        "lemma_raw": "Historia Gothorum",
        "query_names": [
            "Historia Gothorum",
            "Gothorum",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["743"],
        "page_hint_ints": [743],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nHistoria Gothorum. 743.",
    },
    {
        "entry_id": "pl154_ordo_de_amazonibus_729",
        "lemma_raw": "De Amazonibus",
        "query_names": [
            "De Amazonibus",
            "Amazonibus",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["729"],
        "page_hint_ints": [729],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe Amazonibus. 729.",
    },
    {
        "entry_id": "pl154_ordo_de_origine_hunorum_735",
        "lemma_raw": "De origine Hunorum",
        "query_names": [
            "De origine Hunorum",
            "Hunorum",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["735"],
        "page_hint_ints": [735],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe origine Hunorum. 735.",
    },
    {
        "entry_id": "pl154_ordo_historia_longobardorum_787",
        "lemma_raw": "Historia Longobardorum",
        "query_names": [
            "Historia Longobardorum",
            "Longobardorum",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["787"],
        "page_hint_ints": [787],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nHistoria Longobardorum. 787.",
    },
    {
        "entry_id": "pl154_ordo_descriptio_813",
        "lemma_raw": "Descriptio statuæ Karoli Magni",
        "query_names": [
            "Descriptio statuæ Karoli Magni",
            "Karoli Magni",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["813"],
        "page_hint_ints": [813],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDescriptio statuæ Karoli Magni. 813.",
    },
    {
        "entry_id": "pl154_ordo_de_origine_saxonum_885",
        "lemma_raw": "De origine Saxonum",
        "query_names": [
            "De origine Saxonum",
            "Saxonum",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["885"],
        "page_hint_ints": [885],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe origine Saxonum. 885.",
    },
    {
        "entry_id": "pl154_ordo_pars_altera_993",
        "lemma_raw": "PARS ALTERA",
        "query_names": [
            "PARS ALTERA",
            "EKKEHARDI CHRONICON UNIVERSALE",
            "Anni 1106—1126",
        ],
        "page_hints": ["993"],
        "page_hint_ints": [993],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nPARS ALTERA. 993.",
    },
    {
        "entry_id": "pl154_ordo_anni_1106_1126",
        "lemma_raw": "Anni 1106—1126",
        "query_names": [
            "Anni 1106—1126",
            "EKKEHARDI CHRONICON UNIVERSALE",
            "1106 1126",
        ],
        "page_hints": [],
        "page_hint_ints": [],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nAnni 1106—1126.",
    },
    {
        "entry_id": "pl154_ordo_hierosolomita_1039",
        "lemma_raw": "Hierosolomita",
        "query_names": [
            "Hierosolomita",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["1039"],
        "page_hint_ints": [1039],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nHierosolomita. 1039.",
    },
    {
        "entry_id": "pl154_ordo_epistola_erkenbertam_1061",
        "lemma_raw": "Ekkehardi Epistola ad Erkenbertam",
        "query_names": [
            "Ekkehardi Epistola ad Erkenbertam",
            "Erkenbertam",
            "EKKEHARDI CHRONICON UNIVERSALE",
        ],
        "page_hints": ["1061"],
        "page_hint_ints": [1061],
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nEkkehardi Epistola ad Erkenbertam. 1061.",
    },
    {
        "entry_id": "pl154_ordo_prolegomena_1065",
        "lemma_raw": "Prolegomena",
        "query_names": [
            "Prolegomena",
            "GESTA TREVERORUM",
        ],
        "page_hints": ["1065"],
        "page_hint_ints": [1065],
        "context_raw": "GESTA TREVERORUM.\nProlegomena. 1065.",
    },
    {
        "entry_id": "pl154_ordo_incipit_gallorum_1091",
        "lemma_raw": "Incipit de origine Gallorum Trebirorum",
        "query_names": [
            "Incipit de origine Gallorum Trebirorum",
            "Gallorum Trebirorum",
            "GESTA TREVERORUM",
        ],
        "page_hints": ["1091"],
        "page_hint_ints": [1091],
        "context_raw": "GESTA TREVERORUM.\nIncipit de origine Gallorum Trebirorum. 1091.",
    },
    {
        "entry_id": "pl154_ordo_additamentum_1177",
        "lemma_raw": "Additamentum et continuatio prima",
        "query_names": [
            "Additamentum et continuatio prima",
            "GESTA TREVERORUM",
            "continuatio prima",
        ],
        "page_hints": ["1177"],
        "page_hint_ints": [1177],
        "context_raw": "GESTA TREVERORUM.\nAdditamentum et continuatio prima. 1177.",
    },
    {
        "entry_id": "pl154_ordo_gesta_godefridi_1227",
        "lemma_raw": "Gesta Godefridi archiepiscopi",
        "query_names": [
            "Gesta Godefridi archiepiscopi",
            "GODEFRIDI",
            "GESTA TREVERORUM",
        ],
        "page_hints": ["1227"],
        "page_hint_ints": [1227],
        "context_raw": "GESTA TREVERORUM.\nGesta Godefridi archiepiscopi. 1227.",
    },
    {
        "entry_id": "pl154_ordo_ex_translatione_1233",
        "lemma_raw": "Ex translatione sancti Celsi",
        "query_names": [
            "Ex translatione sancti Celsi",
            "Celsi",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1233"],
        "page_hint_ints": [1233],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx translatione sancti Celsi. 1233.",
    },
    {
        "entry_id": "pl154_ordo_miracula_1239",
        "lemma_raw": "Miracula",
        "query_names": [
            "Miracula",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1239"],
        "page_hint_ints": [1239],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nMiracula. 1239.",
    },
    {
        "entry_id": "pl154_ordo_de_abbatis_martini_1245",
        "lemma_raw": "De abbatis Sancti Martini",
        "query_names": [
            "De abbatis Sancti Martini",
            "Sancti Martini",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1245"],
        "page_hint_ints": [1245],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nDe abbatis Sancti Martini. 1245.",
    },
    {
        "entry_id": "pl154_ordo_ex_miraculis_symeonis_1245",
        "lemma_raw": "Ex miraculis sancti Symeonis",
        "query_names": [
            "Ex miraculis sancti Symeonis",
            "Symeonis",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1245"],
        "page_hint_ints": [1245],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx miraculis sancti Symeonis. 1245.",
    },
    {
        "entry_id": "pl154_ordo_ex_vita_agritii_1247",
        "lemma_raw": "Ex vita sancti Agritii",
        "query_names": [
            "Ex vita sancti Agritii",
            "Agritii",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1247"],
        "page_hint_ints": [1247],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx vita sancti Agritii. 1247.",
    },
    {
        "entry_id": "pl154_ordo_vita_et_passio_1251",
        "lemma_raw": "Vita et passio Conradi archiepiscopi",
        "query_names": [
            "Vita et passio Conradi archiepiscopi",
            "Conradi archiepiscopi",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1251"],
        "page_hint_ints": [1251],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nVita et passio Conradi archiepiscopi. 1251.",
    },
    {
        "entry_id": "pl154_ordo_ex_historia_martyrum_1257",
        "lemma_raw": "Ex historia martyrum Treverensium",
        "query_names": [
            "Ex historia martyrum Treverensium",
            "Treverensium",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1257"],
        "page_hint_ints": [1257],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx historia martyrum Treverensium. 1257.",
    },
    {
        "entry_id": "pl154_ordo_ex_miraculis_metodii_1273",
        "lemma_raw": "Ex miraculis S. Metodii",
        "query_names": [
            "Ex miraculis S. Metodii",
            "Metodii",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1273"],
        "page_hint_ints": [1273],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx miraculis S. Metodii. 1273.",
    },
    {
        "entry_id": "pl154_ordo_ex_inventione_1279",
        "lemma_raw": "Ex inventione et miraculis S. Mathiæ",
        "query_names": [
            "Ex inventione et miraculis S. Mathiæ",
            "Mathiæ",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1279"],
        "page_hint_ints": [1279],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx inventione et miraculis S. Mathiæ. 1279.",
    },
    {
        "entry_id": "pl154_ordo_gesta_alberonis_anonymo_1297",
        "lemma_raw": "Gesta Alberonis archiepiscopi. — Gesta metrica, auctore anonymo",
        "query_names": [
            "Gesta Alberonis archiepiscopi",
            "Gesta metrica, auctore anonymo",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1297"],
        "page_hint_ints": [1297],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nGesta Alberonis archiepiscopi. — Gesta metrica, auctore anonymo. 1297.",
    },
    {
        "entry_id": "pl154_ordo_gesta_alberonis_raldiero_1307",
        "lemma_raw": "Gesta Alberonis archiepiscopi, auctore Raldiero",
        "query_names": [
            "Gesta Alberonis archiepiscopi, auctore Raldiero",
            "Raldiero",
            "APPENDIX MONUMENTORUM TREVERENSIUM",
        ],
        "page_hints": ["1307"],
        "page_hint_ints": [1307],
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nGesta Alberonis archiepiscopi, auctore Raldiero. 1307.",
    },
    {
        "entry_id": "pl154_ordo_chronicon_sancti_luberii_1357",
        "lemma_raw": "CHRONICON SANCTI LUBERII ANDAGINENSIS",
        "query_names": [
            "CHRONICON SANCTI LUBERII ANDAGINENSIS",
            "Sancti Luberii",
            "ANDAGINENSIS",
        ],
        "page_hints": ["1357"],
        "page_hint_ints": [1357],
        "context_raw": "CHRONICON SANCTI LUBERII ANDAGINENSIS. 1357.",
    },
]


SECTION_ROWS: list[dict[str, Any]] = [
    {
        "section_key": SECTION_1_KEY,
        "section_order": 1,
        "section_kind": "author_index",
        "heading_raw": SECTION1_HEADING,
        "page_start": None,
        "page_end": None,
        "file_start": SECTION1_FILE,
        "file_end": SECTION1_FILE,
        "section_reason": "Opening ELENCHUS of authors and works; editorially an author index even though the heading is not INDEX AUCTORUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "section_order": 2,
        "section_kind": "ordo_rerum",
        "heading_raw": SECTION2_HEADING,
        "page_start": 1455,
        "page_end": 1456,
        "file_start": SECTION2_FILE,
        "file_end": SECTION2_FILE,
        "section_reason": "Closing ORDO RERUM contents table after the main text, separated from the opening ELENCHUS.",
    },
]


ENTRY_ROWS: list[dict[str, Any]] = [
    # Section 1: ELENCHUS AUCTORUM ET OPERUM
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 1,
        "entry_kind": "heading_group",
        "lemma_raw": "HUGO ABBAS FLAVINIACENSIS",
        "entry_raw": "HUGO ABBAS FLAVINIACENSIS.",
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Author heading in the opening ELENCHUS.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 2,
        "entry_kind": "lemma",
        "lemma_raw": "Chronicon",
        "entry_raw": "Chronicon. Col. 17.",
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nChronicon. Col. 17.",
        "heading_letter": None,
        "inferred_printed_page": 17,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "Col. 17",
        "page_ref_int": 17,
        "page_ref_col": "Col.",
        "ref_kind": "editorial_column",
        "helper_entry_id": "pl154_elenchus_chronicon_017",
        "raw_note": "Column locator in the ELENCHUS.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 3,
        "entry_kind": "heading_group",
        "lemma_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS",
        "entry_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Author heading in the opening ELENCHUS.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 4,
        "entry_kind": "lemma",
        "lemma_raw": "Opusculum de sacramento altaris",
        "entry_raw": "Opusculum de sacramento altaris. 433.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS.\nOpusculum de sacramento altaris. 433.",
        "heading_letter": None,
        "inferred_printed_page": 433,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "433",
        "page_ref_int": 433,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_elenchus_opusculum_433",
        "raw_note": "Work title listed under Wolphelmus.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 5,
        "entry_kind": "lemma",
        "lemma_raw": "Versus de utroque testamento",
        "entry_raw": "Versus de utroque testamento. 433.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS.\nVersus de utroque testamento. 433.",
        "heading_letter": None,
        "inferred_printed_page": 433,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "433",
        "page_ref_int": 433,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_elenchus_versus_433",
        "raw_note": "Same page as the preceding entry in the ELENCHUS.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 6,
        "entry_kind": "heading_group",
        "lemma_raw": "EKKEHARDUS URAUGIENSIS",
        "entry_raw": "EKKEHARDUS URAUGIENSIS.",
        "context_raw": "EKKEHARDUS URAUGIENSIS.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Author heading in the opening ELENCHUS.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 7,
        "entry_kind": "lemma",
        "lemma_raw": "Chronica",
        "entry_raw": "Chronica. 459.",
        "context_raw": "EKKEHARDUS URAUGIENSIS.\nChronica. 459.",
        "heading_letter": None,
        "inferred_printed_page": 459,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "459",
        "page_ref_int": 459,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_elenchus_chronica_459",
        "raw_note": "Work title listed under Ekkehardus.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 8,
        "entry_kind": "heading_group",
        "lemma_raw": "ANONYMUS",
        "entry_raw": "ANONYMUS.",
        "context_raw": "ANONYMUS.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Anonymous author heading in the opening ELENCHUS.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 9,
        "entry_kind": "lemma",
        "lemma_raw": "Gesta Treverorum",
        "entry_raw": "Gesta Treverorum. 1064.",
        "context_raw": "ANONYMUS.\nGesta Treverorum. 1064.",
        "heading_letter": None,
        "inferred_printed_page": 1064,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "1064",
        "page_ref_int": 1064,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_elenchus_gesta_treverorum_1064",
        "raw_note": "Work title listed under anonymous author.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 10,
        "entry_kind": "heading_group",
        "lemma_raw": "ANONYMUS",
        "entry_raw": "ANONYMUS.",
        "context_raw": "ANONYMUS.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Anonymous author heading in the opening ELENCHUS.",
    },
    {
        "section_key": SECTION_1_KEY,
        "entry_order": 11,
        "entry_kind": "lemma",
        "lemma_raw": "Chronicon S. Huberti Andaginensis",
        "entry_raw": "Chronicon S. Huberti Andaginensis. 1337.",
        "context_raw": "ANONYMUS.\nChronicon S. Huberti Andaginensis. 1337.",
        "heading_letter": None,
        "inferred_printed_page": 1337,
        "section_start_file": SECTION1_FILE,
        "editorial_anchor_file": SECTION1_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "1337",
        "page_ref_int": 1337,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_elenchus_chronicon_huberti_1337",
        "raw_note": "Final work title in the opening ELENCHUS.",
    },
    # Section 2: ORDO RERUM
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 1,
        "entry_kind": "heading_group",
        "lemma_raw": "HUGO ABBAS FLAVINIACENSIS",
        "entry_raw": "HUGO ABBAS FLAVINIACENSIS.",
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Main heading in the closing ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 2,
        "entry_kind": "lemma",
        "lemma_raw": "CHRONICON",
        "entry_raw": "CHRONICON. 9.",
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nCHRONICON. 9.",
        "heading_letter": None,
        "inferred_printed_page": 9,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "9",
        "page_ref_int": 9,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_chronicon_009",
        "raw_note": "Opening work title in the ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 3,
        "entry_kind": "lemma",
        "lemma_raw": "Necrologium",
        "entry_raw": "Necrologium. 19.",
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nNecrologium. 19.",
        "heading_letter": None,
        "inferred_printed_page": 19,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "19",
        "page_ref_int": 19,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_necrologium_019",
        "raw_note": "Secondary work title under Hugo.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 4,
        "entry_kind": "lemma",
        "lemma_raw": "Libri primus",
        "entry_raw": "Libri primus. 21.",
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nLibri primus. 21.",
        "heading_letter": None,
        "inferred_printed_page": 21,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "21",
        "page_ref_int": 21,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_libri_primus_021",
        "raw_note": "Book I of the Chronicon.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 5,
        "entry_kind": "lemma",
        "lemma_raw": "Libri secundus",
        "entry_raw": "Libri secundus. 197.",
        "context_raw": "HUGO ABBAS FLAVINIACENSIS.\nLibri secundus. 197.",
        "heading_letter": None,
        "inferred_printed_page": 197,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "197",
        "page_ref_int": 197,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_libri_secundus_197",
        "raw_note": "Book II of the Chronicon.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 6,
        "entry_kind": "heading_group",
        "lemma_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM",
        "entry_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Main heading in the closing ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 7,
        "entry_kind": "lemma",
        "lemma_raw": "Vita B. Wolphelmi",
        "entry_raw": "Vita B. Wolphelmi. 403.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nVita B. Wolphelmi. 403.",
        "heading_letter": None,
        "inferred_printed_page": 403,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "403",
        "page_ref_int": 403,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_vita_wolphelmi_403",
        "raw_note": "First Wolphelmi item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 8,
        "entry_kind": "lemma",
        "lemma_raw": "Observationes præviæ",
        "entry_raw": "Observationes præviæ. 403.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nObservationes præviæ. 403.",
        "heading_letter": None,
        "inferred_printed_page": 403,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "403",
        "page_ref_int": 403,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_observationes_403",
        "raw_note": "Shared page reference with the previous item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 9,
        "entry_kind": "lemma",
        "lemma_raw": "Prologus",
        "entry_raw": "Prologus. 405.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nPrologus. 405.",
        "heading_letter": None,
        "inferred_printed_page": 405,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "405",
        "page_ref_int": 405,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_prologus_405",
        "raw_note": "Wolphelmus subsection.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 10,
        "entry_kind": "lemma",
        "lemma_raw": "Jocipht vita",
        "entry_raw": "Jocipht vita. 407.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nJocipht vita. 407.",
        "heading_letter": None,
        "inferred_printed_page": 407,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "407",
        "page_ref_int": 407,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_jocipht_407",
        "raw_note": "OCR-literal title preserved.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 11,
        "entry_kind": "lemma",
        "lemma_raw": "Opusculum de Sacramento Altaris",
        "entry_raw": "Opusculum de Sacramento Altaris. 433.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nOpusculum de Sacramento Altaris. 433.",
        "heading_letter": None,
        "inferred_printed_page": 433,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "433",
        "page_ref_int": 433,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_opusculum_433",
        "raw_note": "Title repeated in the closing ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 12,
        "entry_kind": "lemma",
        "lemma_raw": "Versus de utroque Testamento",
        "entry_raw": "Versus de utroque Testamento. ibid.",
        "context_raw": "B. WOLPHELMUS ABBAS BRUNSWILLERENSIS PROPE COLONIAM.\nVersus de utroque Testamento. ibid.",
        "heading_letter": None,
        "inferred_printed_page": 433,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "433",
        "page_ref_int": 433,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_versus_433",
        "raw_note": "Inherited from the prior 433 reference; literal ibid. preserved in entry_raw.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 13,
        "entry_kind": "heading_group",
        "lemma_raw": "EKKEHARDUS URAUIGIENSIS",
        "entry_raw": "EKKEHARDUS URAUIGIENSIS.",
        "context_raw": "EKKEHARDUS URAUIGIENSIS.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Main heading in the closing ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 14,
        "entry_kind": "lemma",
        "lemma_raw": "Chronica",
        "entry_raw": "Chronica. ibid.",
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nChronica. ibid.",
        "heading_letter": None,
        "inferred_printed_page": 433,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "433",
        "page_ref_int": 433,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_chronica_433",
        "raw_note": "Inherited page reference resolved from context.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 15,
        "entry_kind": "editorial_note",
        "lemma_raw": "Perutil præfatio",
        "entry_raw": "Perutil præfatio.",
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nPerutil præfatio.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.55,
        "raw_note": "OCR fragment preserved as an editorial note because the line has no explicit locator.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 16,
        "entry_kind": "lemma",
        "lemma_raw": "V. Cl. G. Waitz proœmium",
        "entry_raw": "V. Cl. G. Waitz proœmium. 453.",
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nV. Cl. G. Waitz proœmium. 453.",
        "heading_letter": None,
        "inferred_printed_page": 453,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.72,
        "page_ref_raw": "453",
        "page_ref_int": 453,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_waitz_453",
        "raw_note": "Waitz preface entry.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 17,
        "entry_kind": "lemma",
        "lemma_raw": "CHRONICON WIRZIBURGENSR",
        "entry_raw": "CHRONICON WIRZIBURGENSR. 459.",
        "context_raw": "EKKEHARDUS URAUIGIENSIS.\nCHRONICON WIRZIBURGENSR. 459.",
        "heading_letter": None,
        "inferred_printed_page": 459,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "459",
        "page_ref_int": 459,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_wirziburgensr_459",
        "raw_note": "OCR literal preserved, including the final abbreviation form.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 18,
        "entry_kind": "heading_group",
        "lemma_raw": "EKKEHARDI CHRONICON UNIVERSALE",
        "entry_raw": "EKKEHARDI CHRONICON UNIVERSALE.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Main heading in the closing ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 19,
        "entry_kind": "lemma",
        "lemma_raw": "Epylion (id est abbreviatio) Eusebii de sequenti opere",
        "entry_raw": "Epylion (id est abbreviatio) Eusebii de sequenti opere. 497.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nEpylion (id est abbreviatio) Eusebii de sequenti opere. 497.",
        "heading_letter": None,
        "inferred_printed_page": 497,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "497",
        "page_ref_int": 497,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_epylion_497",
        "raw_note": "Parenthetical editorial description preserved literally.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 20,
        "entry_kind": "lemma",
        "lemma_raw": "Excerptum de Vita Alexandri Magni",
        "entry_raw": "Excerptum de Vita Alexandri Magni. 563.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nExcerptum de Vita Alexandri Magni. 563.",
        "heading_letter": None,
        "inferred_printed_page": 563,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "563",
        "page_ref_int": 563,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_excerptum_563",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 21,
        "entry_kind": "lemma",
        "lemma_raw": "De origine Franconum",
        "entry_raw": "De origine Franconum. 713.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe origine Franconum. 713.",
        "heading_letter": None,
        "inferred_printed_page": 713,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "713",
        "page_ref_int": 713,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_orig_franconum_713",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 22,
        "entry_kind": "lemma",
        "lemma_raw": "Historia Gothorum",
        "entry_raw": "Historia Gothorum. 743.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nHistoria Gothorum. 743.",
        "heading_letter": None,
        "inferred_printed_page": 743,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "743",
        "page_ref_int": 743,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_historia_gothorum_743",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 23,
        "entry_kind": "lemma",
        "lemma_raw": "De Amazonibus",
        "entry_raw": "De Amazonibus. 729.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe Amazonibus. 729.",
        "heading_letter": None,
        "inferred_printed_page": 729,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "729",
        "page_ref_int": 729,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_de_amazonibus_729",
        "raw_note": "Page order in the OCR is non-monotonic; the printed locator is kept literal.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 24,
        "entry_kind": "lemma",
        "lemma_raw": "De origine Hunorum",
        "entry_raw": "De origine Hunorum. 735.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe origine Hunorum. 735.",
        "heading_letter": None,
        "inferred_printed_page": 735,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "735",
        "page_ref_int": 735,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_de_origine_hunorum_735",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 25,
        "entry_kind": "lemma",
        "lemma_raw": "Historia Longobardorum",
        "entry_raw": "Historia Longobardorum. 787.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nHistoria Longobardorum. 787.",
        "heading_letter": None,
        "inferred_printed_page": 787,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "787",
        "page_ref_int": 787,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_historia_longobardorum_787",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 26,
        "entry_kind": "lemma",
        "lemma_raw": "Descriptio statuæ Karoli Magni",
        "entry_raw": "Descriptio statuæ Karoli Magni. 813.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDescriptio statuæ Karoli Magni. 813.",
        "heading_letter": None,
        "inferred_printed_page": 813,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "813",
        "page_ref_int": 813,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_descriptio_813",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 27,
        "entry_kind": "lemma",
        "lemma_raw": "De origine Saxonum",
        "entry_raw": "De origine Saxonum. 885.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nDe origine Saxonum. 885.",
        "heading_letter": None,
        "inferred_printed_page": 885,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "885",
        "page_ref_int": 885,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_de_origine_saxonum_885",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 28,
        "entry_kind": "lemma",
        "lemma_raw": "PARS ALTERA",
        "entry_raw": "PARS ALTERA. 993.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nPARS ALTERA. 993.",
        "heading_letter": None,
        "inferred_printed_page": 993,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "993",
        "page_ref_int": 993,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_pars_altera_993",
        "raw_note": "Editorial subheading with page locator.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 29,
        "entry_kind": "editorial_note",
        "lemma_raw": "Anni 1106—1126",
        "entry_raw": "Anni 1106—1126.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nAnni 1106—1126.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.55,
        "raw_note": "Standalone editorial range preserved as a note because no locator is printed.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 30,
        "entry_kind": "lemma",
        "lemma_raw": "Hierosolomita",
        "entry_raw": "Hierosolomita. 1039.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nHierosolomita. 1039.",
        "heading_letter": None,
        "inferred_printed_page": 1039,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1039",
        "page_ref_int": 1039,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_hierosolomita_1039",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 31,
        "entry_kind": "lemma",
        "lemma_raw": "Ekkehardi Epistola ad Erkenbertam",
        "entry_raw": "Ekkehardi Epistola ad Erkenbertam. 1061.",
        "context_raw": "EKKEHARDI CHRONICON UNIVERSALE.\nEkkehardi Epistola ad Erkenbertam. 1061.",
        "heading_letter": None,
        "inferred_printed_page": 1061,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1061",
        "page_ref_int": 1061,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_epistola_erkenbertam_1061",
        "raw_note": "Work title under Ekkehardi Chronicon Universale.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 32,
        "entry_kind": "heading_group",
        "lemma_raw": "GESTA TREVERORUM",
        "entry_raw": "GESTA TREVERORUM.",
        "context_raw": "GESTA TREVERORUM.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Main heading in the closing ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 33,
        "entry_kind": "lemma",
        "lemma_raw": "Prolegomena",
        "entry_raw": "Prolegomena. 1065.",
        "context_raw": "GESTA TREVERORUM.\nProlegomena. 1065.",
        "heading_letter": None,
        "inferred_printed_page": 1065,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1065",
        "page_ref_int": 1065,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_prolegomena_1065",
        "raw_note": "Prolegomena listed under Gesta Treverorum.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 34,
        "entry_kind": "lemma",
        "lemma_raw": "Incipit de origine Gallorum Trebirorum",
        "entry_raw": "Incipit de origine Gallorum Trebirorum. 1091.",
        "context_raw": "GESTA TREVERORUM.\nIncipit de origine Gallorum Trebirorum. 1091.",
        "heading_letter": None,
        "inferred_printed_page": 1091,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1091",
        "page_ref_int": 1091,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_incipit_gallorum_1091",
        "raw_note": "Work title under Gesta Treverorum.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 35,
        "entry_kind": "lemma",
        "lemma_raw": "Additamentum et continuatio prima",
        "entry_raw": "Additamentum et continuatio prima. 1177.",
        "context_raw": "GESTA TREVERORUM.\nAdditamentum et continuatio prima. 1177.",
        "heading_letter": None,
        "inferred_printed_page": 1177,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1177",
        "page_ref_int": 1177,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_additamentum_1177",
        "raw_note": "Continuation line under Gesta Treverorum.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 36,
        "entry_kind": "lemma",
        "lemma_raw": "Gesta Godefridi archiepiscopi",
        "entry_raw": "Gesta Godefridi archiepiscopi. 1227.",
        "context_raw": "GESTA TREVERORUM.\nGesta Godefridi archiepiscopi. 1227.",
        "heading_letter": None,
        "inferred_printed_page": 1227,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1227",
        "page_ref_int": 1227,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_gesta_godefridi_1227",
        "raw_note": "Final Gesta Treverorum line before the appendix.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 37,
        "entry_kind": "heading_group",
        "lemma_raw": "APPENDIX MONUMENTORUM TREVERENSIUM",
        "entry_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.",
        "heading_letter": None,
        "inferred_printed_page": None,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.97,
        "raw_note": "Appendix heading in the closing ORDO RERUM.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 38,
        "entry_kind": "lemma",
        "lemma_raw": "Ex translatione sancti Celsi",
        "entry_raw": "Ex translatione sancti Celsi. 1233.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx translatione sancti Celsi. 1233.",
        "heading_letter": None,
        "inferred_printed_page": 1233,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1233",
        "page_ref_int": 1233,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_ex_translatione_1233",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 39,
        "entry_kind": "lemma",
        "lemma_raw": "Miracula",
        "entry_raw": "Miracula. 1239.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nMiracula. 1239.",
        "heading_letter": None,
        "inferred_printed_page": 1239,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1239",
        "page_ref_int": 1239,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_miracula_1239",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 40,
        "entry_kind": "lemma",
        "lemma_raw": "De abbatis Sancti Martini",
        "entry_raw": "De abbatis Sancti Martini. 1245.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nDe abbatis Sancti Martini. 1245.",
        "heading_letter": None,
        "inferred_printed_page": 1245,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1245",
        "page_ref_int": 1245,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_de_abbatis_martini_1245",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 41,
        "entry_kind": "lemma",
        "lemma_raw": "Ex miraculis sancti Symeonis",
        "entry_raw": "Ex miraculis sancti Symeonis. 1245.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx miraculis sancti Symeonis. 1245.",
        "heading_letter": None,
        "inferred_printed_page": 1245,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1245",
        "page_ref_int": 1245,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_ex_miraculis_symeonis_1245",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 42,
        "entry_kind": "lemma",
        "lemma_raw": "Ex vita sancti Agritii",
        "entry_raw": "Ex vita sancti Agritii. 1247.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx vita sancti Agritii. 1247.",
        "heading_letter": None,
        "inferred_printed_page": 1247,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1247",
        "page_ref_int": 1247,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_ex_vita_agritii_1247",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 43,
        "entry_kind": "lemma",
        "lemma_raw": "Vita et passio Conradi archiepiscopi",
        "entry_raw": "Vita et passio Conradi archiepiscopi. 1251.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nVita et passio Conradi archiepiscopi. 1251.",
        "heading_letter": None,
        "inferred_printed_page": 1251,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1251",
        "page_ref_int": 1251,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_vita_et_passio_1251",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 44,
        "entry_kind": "lemma",
        "lemma_raw": "Ex historia martyrum Treverensium",
        "entry_raw": "Ex historia martyrum Treverensium. 1257.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx historia martyrum Treverensium. 1257.",
        "heading_letter": None,
        "inferred_printed_page": 1257,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1257",
        "page_ref_int": 1257,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_ex_historia_martyrum_1257",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 45,
        "entry_kind": "lemma",
        "lemma_raw": "Ex miraculis S. Metodii",
        "entry_raw": "Ex miraculis S. Metodii. 1273.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx miraculis S. Metodii. 1273.",
        "heading_letter": None,
        "inferred_printed_page": 1273,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1273",
        "page_ref_int": 1273,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_ex_miraculis_metodii_1273",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 46,
        "entry_kind": "lemma",
        "lemma_raw": "Ex inventione et miraculis S. Mathiæ",
        "entry_raw": "Ex inventione et miraculis S. Mathiæ. 1279.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nEx inventione et miraculis S. Mathiæ. 1279.",
        "heading_letter": None,
        "inferred_printed_page": 1279,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1279",
        "page_ref_int": 1279,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_ex_inventione_1279",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 47,
        "entry_kind": "lemma",
        "lemma_raw": "Gesta Alberonis archiepiscopi. — Gesta metrica, auctore anonymo",
        "entry_raw": "Gesta Alberonis archiepiscopi. — Gesta metrica, auctore anonymo. 1297.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nGesta Alberonis archiepiscopi. — Gesta metrica, auctore anonymo. 1297.",
        "heading_letter": None,
        "inferred_printed_page": 1297,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1297",
        "page_ref_int": 1297,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_gesta_alberonis_anonymo_1297",
        "raw_note": "Compound appendix title preserved literally.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 48,
        "entry_kind": "lemma",
        "lemma_raw": "Gesta Alberonis archiepiscopi, auctore Raldiero",
        "entry_raw": "Gesta Alberonis archiepiscopi, auctore Raldiero. 1307.",
        "context_raw": "APPENDIX MONUMENTORUM TREVERENSIUM.\nGesta Alberonis archiepiscopi, auctore Raldiero. 1307.",
        "heading_letter": None,
        "inferred_printed_page": 1307,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1307",
        "page_ref_int": 1307,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_gesta_alberonis_raldiero_1307",
        "raw_note": "Appendix item.",
    },
    {
        "section_key": SECTION_2_KEY,
        "entry_order": 49,
        "entry_kind": "lemma",
        "lemma_raw": "CHRONICON SANCTI LUBERII ANDAGINENSIS",
        "entry_raw": "CHRONICON SANCTI LUBERII ANDAGINENSIS. 1357.",
        "context_raw": "CHRONICON SANCTI LUBERII ANDAGINENSIS. 1357.",
        "heading_letter": None,
        "inferred_printed_page": 1357,
        "section_start_file": SECTION2_FILE,
        "editorial_anchor_file": SECTION2_FILE,
        "target_file_best": None,
        "confidence": 0.68,
        "page_ref_raw": "1357",
        "page_ref_int": 1357,
        "page_ref_col": None,
        "ref_kind": "editorial_page",
        "helper_entry_id": "pl154_ordo_chronicon_sancti_luberii_1357",
        "raw_note": "Final ORDO RERUM line.",
    },
]


TARGET_FILE_OVERRIDES: dict[str, str] = {
    "pl154_elenchus_opusculum_433": str(SOURCE_ROOT / "fe3fed92-e0fb-4933-9830-ebe76ab06b7e-221.txt"),
    "pl154_elenchus_versus_433": str(SOURCE_ROOT / "fe3fed92-e0fb-4933-9830-ebe76ab06b7e-221.txt"),
    "pl154_elenchus_chronica_459": str(SOURCE_ROOT / "fe3fed92-e0fb-4933-9830-ebe76ab06b7e-234.txt"),
    "pl154_elenchus_gesta_treverorum_1064": str(SOURCE_ROOT / "e2d6b339-2fa1-4254-af28-312dae0c96bb-536.txt"),
    "pl154_elenchus_chronicon_huberti_1337": str(SOURCE_ROOT / "8905129f-9a13-4287-99fb-578e13661605-673.txt"),
    "pl154_ordo_chronicon_009": str(SOURCE_ROOT / "3b651b79-9fc4-4a87-a056-9723294703d9-009.txt"),
    "pl154_ordo_opusculum_433": str(SOURCE_ROOT / "fe3fed92-e0fb-4933-9830-ebe76ab06b7e-221.txt"),
    "pl154_ordo_versus_433": str(SOURCE_ROOT / "fe3fed92-e0fb-4933-9830-ebe76ab06b7e-221.txt"),
    "pl154_ordo_chronica_433": str(SOURCE_ROOT / "fe3fed92-e0fb-4933-9830-ebe76ab06b7e-221.txt"),
    "pl154_ordo_jocipht_407": str(SOURCE_ROOT / "fe3fed92-e0fb-4933-9830-ebe76ab06b7e-208.txt"),
}

TARGET_FILE_NULLS = {
    "pl154_ordo_additamentum_1177",
}


def build_helper_request() -> dict[str, Any]:
    helper_entries: list[dict[str, Any]] = []
    for row in ENTRY_ROWS:
        page_hints = []
        page_hint_ints = []
        if row.get("page_ref_int") is not None:
            page_hints = [row["page_ref_raw"] or str(row["page_ref_int"])]
            page_hint_ints = [int(row["page_ref_int"])]
        if not page_hints:
            continue
        helper_entries.append(
            {
                "entry_id": row["helper_entry_id"],
                "lemma_raw": row["lemma_raw"],
                "query_names": row.get("query_names", [row["lemma_raw"]]),
                "page_hints": page_hints,
                "page_hint_ints": page_hint_ints,
                "context_raw": row["context_raw"],
            }
        )
    return {
        "volume_id": VOLUME_ID,
        "source_root": str(SOURCE_ROOT),
        "options": {"top_k": 5, "adjacency_window": 2},
        "entries": helper_entries,
    }


def helper_index(helper_output: dict[str, Any]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for item in helper_output.get("entries", []):
        entry_id = item.get("entry_id")
        if entry_id:
            result[str(entry_id)] = item
    return result


def helper_summary(item: dict[str, Any]) -> dict[str, Any]:
    best = item.get("best_candidate") or {}
    candidates = item.get("candidates") or []
    top_candidates = []
    for cand in candidates[:3]:
        top_candidates.append(
            {
                "file": cand.get("file"),
                "probability": cand.get("probability"),
                "candidate_role": cand.get("candidate_role"),
                "inferred_printed_page": cand.get("inferred_printed_page"),
                "reason_summary": cand.get("reason_summary"),
                "evidence_kinds": [ev.get("kind") for ev in cand.get("evidence", [])[:4]],
            }
        )
    return {
        "helper_status": item.get("status"),
        "helper_best_file": best.get("file"),
        "helper_best_probability": best.get("probability"),
        "helper_candidate_role": best.get("candidate_role"),
        "helper_reason_summary": best.get("reason_summary"),
        "helper_top_candidates": top_candidates,
    }


def build_payload(helper_output_json: Path, intermediate_dir: Path) -> dict[str, Any]:
    helper_output = read_json(helper_output_json, {})
    helper_map = helper_index(helper_output)

    sections: list[dict[str, Any]] = []
    for section in SECTION_ROWS:
        sections.append(
            {
                "section_key": section["section_key"],
                "volume_id": VOLUME_ID,
                "work_key": None,
                "section_order": section["section_order"],
                "section_kind": section["section_kind"],
                "heading_raw": section["heading_raw"],
                "heading_norm": sort_norm(section["heading_raw"]),
                "heading_letter": None,
                "page_start": section["page_start"],
                "page_end": section["page_end"],
                "file_start": str(section["file_start"]),
                "file_end": str(section["file_end"]),
                "confidence": 0.98 if section["section_kind"] == "ordo_rerum" else 0.97,
                "raw_json": {
                    "section_kind_reason": section["section_reason"],
                    "evidence_files": [str(section["file_start"]), str(section["file_end"])],
                },
            }
        )

    entries: list[dict[str, Any]] = []
    refs: list[dict[str, Any]] = []
    for idx, row in enumerate(ENTRY_ROWS, start=1):
        entry_key = f"{VOLUME_ID}:entry:{idx:04d}"
        helper_entry = helper_map.get(row.get("helper_entry_id") or "")
        helper_best = (helper_entry or {}).get("best_candidate") or {}
        helper_entry_id = row.get("helper_entry_id") or ""
        target_file_best = TARGET_FILE_OVERRIDES.get(
            helper_entry_id,
            helper_best.get("file") if helper_best else row.get("target_file_best"),
        )
        if helper_entry_id in TARGET_FILE_NULLS:
            target_file_best = None
        raw_json = {
            "source_line": row["entry_raw"],
            "section_kind": "author_index" if row["section_key"] == SECTION_1_KEY else "ordo_rerum",
        }
        raw_note = row.get("raw_note")
        if raw_note:
            raw_json["note"] = raw_note
        if helper_entry:
            raw_json.update(helper_summary(helper_entry))
            raw_json["helper_entry_id"] = row["helper_entry_id"]
            raw_json["helper_used"] = True
            if helper_entry_id in TARGET_FILE_OVERRIDES:
                raw_json["target_file_override"] = target_file_best
            if helper_entry_id in TARGET_FILE_NULLS:
                raw_json["target_file_override"] = None
        else:
            raw_json["helper_used"] = False

        entries.append(
            {
                "entry_key": entry_key,
                "section_key": row["section_key"],
                "parent_node_key": None,
                "entry_order": row["entry_order"],
                "entry_kind": row["entry_kind"],
                "lemma_raw": row["lemma_raw"],
                "lemma_display": row["lemma_raw"],
                "lemma_norm": normalize(row["lemma_raw"]).lower() if normalize(row["lemma_raw"]) else None,
                "lemma_sort": sort_norm(row["lemma_raw"]),
                "entry_raw": row["entry_raw"],
                "context_raw": row["context_raw"],
                "heading_letter": None,
                "inferred_printed_page": row.get("inferred_printed_page"),
                "section_start_file": str(row["section_start_file"]),
                "editorial_anchor_file": str(row["editorial_anchor_file"]),
                "target_file_best": target_file_best,
                "confidence": row["confidence"] if helper_entry is None else max(row["confidence"], 0.68 if helper_best else row["confidence"]),
                "raw_json": raw_json,
            }
        )

        if row.get("page_ref_int") is not None:
            ref_raw = row.get("page_ref_raw") or str(row["page_ref_int"])
            ref_raw_literal = ref_raw
            ref_raw = str(row["page_ref_int"]) if row.get("page_ref_col") is None else row["page_ref_raw"]
            ref_payload = {
                "entry_key": entry_key,
                "ref_order": 1,
                "ref_kind": row["ref_kind"],
                "ref_raw": ref_raw,
                "page_ref_raw": row.get("page_ref_raw") or ref_raw,
                "page_ref_int": row.get("page_ref_int"),
                "page_ref_col": row.get("page_ref_col"),
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": target_file_best,
                "target_file_probability": helper_best.get("probability") if helper_best else None,
                "section_start_file": str(row["section_start_file"]),
                "editorial_anchor_file": str(row["editorial_anchor_file"]),
                "confidence": row["confidence"] if helper_entry is None else max(row["confidence"], 0.68 if helper_best else row["confidence"]),
                "raw_json": {
                    "source_line": row["entry_raw"],
                    "page_ref_literal": ref_raw_literal,
                    "helper_used": bool(helper_entry),
                },
            }
            if helper_entry:
                ref_payload["raw_json"].update(helper_summary(helper_entry))
                ref_payload["raw_json"]["helper_entry_id"] = row["helper_entry_id"]
            refs.append(ref_payload)

    coverage = {
        "entries_status": "recovered_with_residual_ambiguity",
        "entries_status_reason": (
            "Recovered the opening ELENCHUS author index and the closing ORDO RERUM contents table from OCR. "
            "Material locator-bearing entries were resolved with the helper, while non-locator headings and "
            "editorial fragments such as Perutil præfatio. and Anni 1106—1126. were preserved explicitly."
        ),
        "evidence_files": [
            str(SECTION1_FILE),
            str(SOURCE_ROOT / "3b651b79-9fc4-4a87-a056-9723294703d9-013.txt"),
            str(SOURCE_ROOT / "3b651b79-9fc4-4a87-a056-9723294703d9-014.txt"),
            str(SOURCE_ROOT / "3b651b79-9fc4-4a87-a056-9723294703d9-015.txt"),
            str(SOURCE_ROOT / "3b651b79-9fc4-4a87-a056-9723294703d9-017.txt"),
            str(SECTION2_FILE),
        ],
    }

    notes = [
        "Section 1 is the ELENCHUS AUCTORUM ET OPERUM opening inventory and is modeled as author_index.",
        "Section 2 is the closing ORDO RERUM contents table; the printed page span 1455-1456 is preserved on the section.",
        "The page/column locator in the ELENCHUS entry for Chronicon is kept separate from editorial page locators.",
    ]

    return {
        "schema_version": 1,
        "generated_at": now_iso(),
        "volume": {
            "volume_id": VOLUME_ID,
            "collection": COLLECTION,
            "source_root": str(SOURCE_ROOT),
            "volume_label": VOLUME_LABEL,
        },
        "sections": sections,
        "nodes": [],
        "entries": entries,
        "refs": refs,
        "scripture_refs": [],
        "coverage": coverage,
        "notes": notes,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="Build the PL154 alphabetical payload and helper request.")
    ap.add_argument("--write-helper-request", action="store_true", help="Write the helper request JSON and exit.")
    ap.add_argument("--build-payload", action="store_true", help="Build the final payload JSON.")
    ap.add_argument("--helper-request-json", type=Path, required=True)
    ap.add_argument("--helper-output-json", type=Path, default=ROOT / "data/alphabetical_index_payloads/PL154_helper_output.json")
    ap.add_argument("--intermediate-dir", type=Path, required=True)
    ap.add_argument("--output-file", type=Path, default=ROOT / "data/alphabetical_index_payloads/PL154_alphabetical_indices.json")
    args = ap.parse_args()

    if args.write_helper_request:
        write_json(args.helper_request_json, build_helper_request())
        todo = {
            "volume_id": VOLUME_ID,
            "updated_at": now_iso(),
            "current_focus": "Generate helper output for PL154 and assemble the final alphabetical payload.",
            "completed": [
                "OCR tail inspected",
                "opening ELENCHUS and closing ORDO RERUM sections identified",
            ],
            "pending": [
                "run index_target_locator on the helper request",
                "build the final JSON payload from OCR and helper evidence",
            ],
            "blocked": [],
            "notes": [
                "Keep the ELENCHUS author index separate from the volume-end ORDO RERUM table.",
                "Preserve column/page distinction for the Chronicon entry in the ELENCHUS.",
            ],
        }
        write_json(args.intermediate_dir / "todo.json", todo)
        return

    if args.build_payload:
        payload = build_payload(args.helper_output_json, args.intermediate_dir)
        write_json(args.output_file, payload)
        return

    raise SystemExit("Specify either --write-helper-request or --build-payload.")


if __name__ == "__main__":
    main()
