# Usage: python scripts/pipeline_index_extraction/build_pg027_alphabetical_payload.py
# Assemble the PG027 alphabetical-index payload from the OCR page 713 index
# and the helper output in data/alphabetical_index_payloads/PG027_helper_output.json.

from __future__ import annotations

import json
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path("/homessddata/Projects/pdfocr")
SOURCE_ROOT = ROOT / "teste/PG027/text"
SECTION_FILE = SOURCE_ROOT / "d522e5b8-afda-421a-bba0-e241fb78d7b5-713.txt"
HELPER_OUTPUT = ROOT / "data/alphabetical_index_payloads/PG027_helper_output.json"
OUTPUT_FILE = ROOT / "data/alphabetical_index_payloads/PG027_alphabetical_indices.json"


def norm_text(text: str) -> str:
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")
    text = text.lower()
    text = re.sub(r"[^\w\s\u0370-\u03ff\u1f00-\u1fff]", " ", text, flags=re.UNICODE)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def helper_summary(helper_map: dict, entry_id: str) -> dict | None:
    item = helper_map.get(entry_id)
    if not item:
        return None
    candidates = []
    for cand in item.get("candidates", [])[:3]:
        evid_kinds = [ev.get("kind") for ev in cand.get("evidence", [])[:5]]
        candidates.append(
            {
                "file": cand.get("file"),
                "probability": cand.get("probability"),
                "candidate_role": cand.get("candidate_role"),
                "reason_summary": cand.get("reason_summary"),
                "evidence_kinds": evid_kinds,
            }
        )
    return {
        "status": item.get("status"),
        "candidate_role": item.get("best_candidate", {}).get("candidate_role"),
        "reason_summary": item.get("best_candidate", {}).get("reason_summary"),
        "best_candidate": {
            "file": item.get("best_candidate", {}).get("file"),
            "probability": item.get("best_candidate", {}).get("probability"),
            "candidate_role": item.get("best_candidate", {}).get("candidate_role"),
            "reason_summary": item.get("best_candidate", {}).get("reason_summary"),
        },
        "top_candidates": candidates,
    }


helper_data = json.loads(HELPER_OUTPUT.read_text())
helper_map = {entry["entry_id"]: entry for entry in helper_data["entries"]}


section_key = "PG027:alpha:foreign_terms:001"
section_start_file = str(SECTION_FILE)

entries_spec = [
    {
        "entry_key": f"{section_key}:entry:0001",
        "entry_id": "pg027_001",
        "entry_order": 1,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀγαπητός",
        "lemma_display": "Ἀγαπητός",
        "lemma_norm": norm_text("Ἀγαπητός"),
        "lemma_sort": norm_text("Ἀγαπητός"),
        "entry_raw": "Ἀγαπητός, idem qui, Μονογενής, Unigenitus. Ἀγαπητὸς, item hac sententia usu venit, col. 232 B: Ἄλλαι γόθοις καὶ τρόμοις ἐπεπέσσε τῷ προφήτῃ ὄρωντʼ τὸν Ἀγαπητὸν τοῦ θεοῦ τοιαύτα ὑπὸ τῶν ἀσεβῶν πάσχοντα.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-122.txt"),
        "confidence": 0.82,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_001",
            "selected_target_file_reason": "helper best candidate matches the quoted entry at col. 232 B.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 232 B",
                "page_ref_raw": "col. 232 B",
                "page_ref_int": 232,
                "page_ref_col": "B",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-122.txt"),
                "target_file_probability": 0.81906,
                "confidence": 0.82,
                "raw_json": {
                    "helper_entry_id": "pg027_001",
                    "source_token": "col. 232 B",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0002",
        "entry_id": "pg027_002",
        "entry_order": 2,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀγιοπρεπής",
        "lemma_display": "Ἀγιοπρεπής",
        "lemma_norm": norm_text("Ἀγιοπρεπής"),
        "lemma_sort": norm_text("Ἀγιοπρεπής"),
        "entry_raw": "Ἀγιοπρεπής, οὖς, Sanctus, col. 92 D.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-052.txt"),
        "confidence": 0.81,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_002",
            "selected_target_file_reason": "helper best candidate resolves the col. 92 D citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 92 D",
                "page_ref_raw": "col. 92 D",
                "page_ref_int": 92,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-052.txt"),
                "target_file_probability": 0.80539,
                "confidence": 0.81,
                "raw_json": {
                    "helper_entry_id": "pg027_002",
                    "source_token": "col. 92 D",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0003",
        "entry_id": "pg027_003",
        "entry_order": 3,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀγγιθέρος",
        "lemma_display": "Ἀγγιθέρος",
        "lemma_norm": norm_text("Ἀγγιθέρος"),
        "lemma_sort": norm_text("Ἀγγιθέρος"),
        "entry_raw": "Ἀγγιθέρος, foribus propinquus, et per metaplo- ram, congriens, accommodatus, col. 540 C.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-277.txt"),
        "confidence": 0.50,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_003",
            "selected_target_file_reason": "helper left the case borderline, but file 277 is the best OCR page for col. 540 C after local drift checks.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 540 C",
                "page_ref_raw": "col. 540 C",
                "page_ref_int": 540,
                "page_ref_col": "C",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-277.txt"),
                "target_file_probability": 0.503759,
                "confidence": 0.50,
                "raw_json": {
                    "helper_entry_id": "pg027_003",
                    "source_token": "col. 540 C",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0004",
        "entry_id": "pg027_004",
        "entry_order": 4,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀγγαπεύομαι",
        "lemma_display": "Ἀγγαπεύομαι",
        "lemma_norm": norm_text("Ἀγγαπεύομαι"),
        "lemma_sort": norm_text("Ἀγγαπεύομαι"),
        "entry_raw": "Ἀγγαπεύομαι, vicissim capior, col. 169 D.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-091.txt"),
        "confidence": 0.80,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_004",
            "selected_target_file_reason": "helper best candidate resolves the col. 169 D citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 169 D",
                "page_ref_raw": "col. 169 D",
                "page_ref_int": 169,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-091.txt"),
                "target_file_probability": 0.802336,
                "confidence": 0.80,
                "raw_json": {
                    "helper_entry_id": "pg027_004",
                    "source_token": "col. 169 D",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0005",
        "entry_id": "pg027_005",
        "entry_order": 5,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀγαπημάκος",
        "lemma_display": "Ἀγαπημάκος",
        "lemma_norm": norm_text("Ἀγαπημάκος"),
        "lemma_sort": norm_text("Ἀγαπημάκος"),
        "entry_raw": "Ἀγαπημάκος, qui inclinatus et inflexus non est, col. 547 A.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-280.txt"),
        "confidence": 0.64,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_005",
            "selected_target_file_reason": "helper best candidate is acceptable despite moderate page drift.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 547 A",
                "page_ref_raw": "col. 547 A",
                "page_ref_int": 547,
                "page_ref_col": "A",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-280.txt"),
                "target_file_probability": 0.639874,
                "confidence": 0.64,
                "raw_json": {
                    "helper_entry_id": "pg027_005",
                    "source_token": "col. 547 A",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0006",
        "entry_id": "pg027_006",
        "entry_order": 6,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀλευδοκέω",
        "lemma_display": "Ἀλευδοκέω",
        "lemma_norm": norm_text("Ἀλευδοκέω"),
        "lemma_sort": norm_text("Ἀλευδοκέω"),
        "entry_raw": "Ἀλευδοκέω, despero, col. 336 A.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-174.txt"),
        "confidence": 0.81,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_006",
            "selected_target_file_reason": "helper best candidate resolves the col. 336 A citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 336 A",
                "page_ref_raw": "col. 336 A",
                "page_ref_int": 336,
                "page_ref_col": "A",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-174.txt"),
                "target_file_probability": 0.814528,
                "confidence": 0.81,
                "raw_json": {
                    "helper_entry_id": "pg027_006",
                    "source_token": "col. 336 A",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0007",
        "entry_id": "pg027_007",
        "entry_order": 7,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀποθαυμάζω",
        "lemma_display": "Ἀποθαυμάζω",
        "lemma_norm": norm_text("Ἀποθαυμάζω"),
        "lemma_sort": norm_text("Ἀποθαυμάζω"),
        "entry_raw": "Ἀποθαυμάζω, admiror, admirationem verbis exprimo, psal. cxxxviii.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": section_start_file,
        "confidence": 0.94,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "note": "scripture citation only; no material page locator in the index line.",
        },
    },
    {
        "entry_key": f"{section_key}:entry:0008",
        "entry_id": "pg027_008",
        "entry_order": 8,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀποκλεισμός",
        "lemma_display": "Ἀποκλεισμός",
        "lemma_norm": norm_text("Ἀποκλεισμός"),
        "lemma_sort": norm_text("Ἀποκλεισμός"),
        "entry_raw": "Ἀποκλεισμός, conclusio, col. 540 D.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-277.txt"),
        "confidence": 0.97,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_007",
            "selected_target_file_reason": "helper best candidate resolves the col. 540 D citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 540 D",
                "page_ref_raw": "col. 540 D",
                "page_ref_int": 540,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-277.txt"),
                "target_file_probability": 0.968243,
                "confidence": 0.97,
                "raw_json": {
                    "helper_entry_id": "pg027_007",
                    "source_token": "col. 540 D",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0009",
        "entry_id": "pg027_009",
        "entry_order": 9,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀπολιθόωμαι",
        "lemma_display": "Ἀπολιθόωμαι",
        "lemma_norm": norm_text("Ἀπολιθόωμαι"),
        "lemma_sort": norm_text("Ἀπολιθόωμαι"),
        "entry_raw": "Ἀπολιθόωμαι, lapidesco, lapidis instar durus sum, psal. cxxxiv.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": section_start_file,
        "confidence": 0.94,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "note": "scripture citation only; no material page locator in the index line.",
        },
    },
    {
        "entry_key": f"{section_key}:entry:0010",
        "entry_id": "pg027_010",
        "entry_order": 10,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀποταμεύομαι",
        "lemma_display": "Ἀποταμεύομαι",
        "lemma_norm": norm_text("Ἀποταμεύομαι"),
        "lemma_sort": norm_text("Ἀποταμεύομαι"),
        "entry_raw": "Ἀποταμεύομαι, mecum reputo, in intimis coriuis repono considerandum, col. 541 A.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-277.txt"),
        "confidence": 0.94,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_008",
            "selected_target_file_reason": "helper best candidate resolves the col. 541 A citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 541 A",
                "page_ref_raw": "col. 541 A",
                "page_ref_int": 541,
                "page_ref_col": "A",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-277.txt"),
                "target_file_probability": 0.942402,
                "confidence": 0.94,
                "raw_json": {
                    "helper_entry_id": "pg027_008",
                    "source_token": "col. 541 A",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0011",
        "entry_id": "pg027_011",
        "entry_order": 11,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀποκείμετα τῶν ἐννυπνίων",
        "lemma_display": "Ἀποκείμετα τῶν ἐννυπνίων",
        "lemma_norm": norm_text("Ἀποκείμετα τῶν ἐννυπνίων"),
        "lemma_sort": norm_text("Ἀποκείμετα τῶν ἐννυπνίων"),
        "entry_raw": "Ἀποκείμετα τῶν ἐννυπνίων, somniorum prædi- ctio nes, col. 444 C.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "576a4356-6bcf-4b9d-a670-5966bf4297a4-228.txt"),
        "confidence": 1.00,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_009",
            "selected_target_file_reason": "helper best candidate resolves the col. 444 C citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 444 C",
                "page_ref_raw": "col. 444 C",
                "page_ref_int": 444,
                "page_ref_col": "C",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "576a4356-6bcf-4b9d-a670-5966bf4297a4-228.txt"),
                "target_file_probability": 0.999667,
                "confidence": 1.00,
                "raw_json": {
                    "helper_entry_id": "pg027_009",
                    "source_token": "col. 444 C",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0012",
        "entry_id": "pg027_012",
        "entry_order": 12,
        "entry_kind": "lemma",
        "lemma_raw": "Ἀρχιτέαρος",
        "lemma_display": "Ἀρχιτέαρος",
        "lemma_norm": norm_text("Ἀρχιτέαρος"),
        "lemma_sort": norm_text("Ἀρχιτέαρος"),
        "entry_raw": "Ἀρχιτέαρος, in amicis primus, amicissimus, col. 77 C.",
        "context_raw": None,
        "heading_letter": "A",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-045.txt"),
        "confidence": 1.00,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_010",
            "selected_target_file_reason": "helper best candidate resolves the col. 77 C citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 77 C",
                "page_ref_raw": "col. 77 C",
                "page_ref_int": 77,
                "page_ref_col": "C",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-045.txt"),
                "target_file_probability": 0.999673,
                "confidence": 1.00,
                "raw_json": {
                    "helper_entry_id": "pg027_010",
                    "source_token": "col. 77 C",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0013",
        "entry_id": "pg027_013",
        "entry_order": 13,
        "entry_kind": "lemma",
        "lemma_raw": "Δισθολόγιος τόπος",
        "lemma_display": "Δισθολόγιος τόπος",
        "lemma_norm": norm_text("Δισθολόγιος τόπος"),
        "lemma_sort": norm_text("Δισθολόγιος τόπος"),
        "entry_raw": "Δισθολόγιος τόπος, locus ex lapidibus electis con- structus, col. 357 C.",
        "context_raw": None,
        "heading_letter": "Δ",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "576a4356-6bcf-4b9d-a670-5966bf4297a4-185.txt"),
        "confidence": 1.00,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_011",
            "selected_target_file_reason": "helper best candidate resolves the col. 357 C citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 357 C",
                "page_ref_raw": "col. 357 C",
                "page_ref_int": 357,
                "page_ref_col": "C",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "576a4356-6bcf-4b9d-a670-5966bf4297a4-185.txt"),
                "target_file_probability": 0.999255,
                "confidence": 1.00,
                "raw_json": {
                    "helper_entry_id": "pg027_011",
                    "source_token": "col. 357 C",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0014",
        "entry_id": "pg027_014",
        "entry_order": 14,
        "entry_kind": "lemma",
        "lemma_raw": "Μακροημέρευσις",
        "lemma_display": "Μακροημέρευσις",
        "lemma_norm": norm_text("Μακροημέρευσις"),
        "lemma_sort": norm_text("Μακροημέρευσις"),
        "entry_raw": "Μακροημέρευσις, longitudo dierum, col. 128 D.",
        "context_raw": None,
        "heading_letter": "M",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-071.txt"),
        "confidence": 0.97,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_012",
            "selected_target_file_reason": "helper best candidate resolves the col. 128 D citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 128 D",
                "page_ref_raw": "col. 128 D",
                "page_ref_int": 128,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-071.txt"),
                "target_file_probability": 0.969902,
                "confidence": 0.97,
                "raw_json": {
                    "helper_entry_id": "pg027_012",
                    "source_token": "col. 128 D",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0015",
        "entry_id": "pg027_015",
        "entry_order": 15,
        "entry_kind": "lemma",
        "lemma_raw": "Ματαιότης",
        "lemma_display": "Ματαιότης",
        "lemma_norm": norm_text("Ματαιότης"),
        "lemma_sort": norm_text("Ματαιότης"),
        "entry_raw": "Ματαιότης, vanitas, col. 141 B.",
        "context_raw": None,
        "heading_letter": "M",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-100.txt"),
        "confidence": 0.91,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_013",
            "selected_target_file_reason": "helper best candidate resolves the col. 141 B citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 141 B",
                "page_ref_raw": "col. 141 B",
                "page_ref_int": 141,
                "page_ref_col": "B",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-100.txt"),
                "target_file_probability": 0.91099,
                "confidence": 0.91,
                "raw_json": {
                    "helper_entry_id": "pg027_013",
                    "source_token": "col. 141 B",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0016",
        "entry_id": "pg027_016",
        "entry_order": 16,
        "entry_kind": "lemma",
        "lemma_raw": "Μεταχειρίζεσθαι ἑαυτὸν ἀργόν",
        "lemma_display": "Μεταχειρίζεσθαι ἑαυτὸν ἀργόν",
        "lemma_norm": norm_text("Μεταχειρίζεσθαι ἑαυτὸν ἀργόν"),
        "lemma_sort": norm_text("Μεταχειρίζεσθαι ἑαυτὸν ἀργόν"),
        "entry_raw": "Μεταχειρίζεσθαι ἑαυτὸν ἀργόν, qui laqueo se pra- foccavit, de Juda dictum, col. 457 A.",
        "context_raw": None,
        "heading_letter": "M",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "576a4356-6bcf-4b9d-a670-5966bf4297a4-235.txt"),
        "confidence": 0.97,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_014",
            "selected_target_file_reason": "helper best candidate resolves the col. 457 A citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 457 A",
                "page_ref_raw": "col. 457 A",
                "page_ref_int": 457,
                "page_ref_col": "A",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "576a4356-6bcf-4b9d-a670-5966bf4297a4-235.txt"),
                "target_file_probability": 0.970123,
                "confidence": 0.97,
                "raw_json": {
                    "helper_entry_id": "pg027_014",
                    "source_token": "col. 457 A",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0017",
        "entry_id": "pg027_017",
        "entry_order": 17,
        "entry_kind": "lemma",
        "lemma_raw": "Olxoxumla",
        "lemma_display": "Οἰκονομία",
        "lemma_norm": "οἰκονομια",
        "lemma_sort": "οἰκονομια",
        "entry_raw": "Olxoxumla, sape pro Incarnatione usu venit. Vulga- rius autem significat totam seriem actionum Chri- sti ut col. 300 C. Dicitur etiam, οἰκονoμία τοῦ πάθους, œconomia passionis, οἰκονομία τοῦ σταυ- ροῦ, œconomia crucis, col. 325 D.",
        "context_raw": None,
        "heading_letter": "M",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-170.txt"),
        "confidence": 0.99,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_015",
            "ocr_note": "Lemma OCR is corrupt; normalized from the contextual gloss to the common term for economy/incarnation.",
            "selected_target_file_reason": "helper supports two separate locators; 325 D is the best match for the top candidate and 300 C was split to the second candidate.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 300 C",
                "page_ref_raw": "col. 300 C",
                "page_ref_int": 300,
                "page_ref_col": "C",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-156.txt"),
                "target_file_probability": 0.013444,
                "confidence": 0.84,
                "raw_json": {
                    "helper_entry_id": "pg027_015",
                    "source_token": "col. 300 C",
                    "helper_rank": 2,
                },
            },
            {
                "ref_order": 2,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 325 D",
                "page_ref_raw": "col. 325 D",
                "page_ref_int": 325,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-170.txt"),
                "target_file_probability": 0.985498,
                "confidence": 0.99,
                "raw_json": {
                    "helper_entry_id": "pg027_015",
                    "source_token": "col. 325 D",
                    "helper_rank": 1,
                },
            },
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0018",
        "entry_id": "pg027_018",
        "entry_order": 18,
        "entry_kind": "lemma",
        "lemma_raw": "Παρεκτροπή",
        "lemma_display": "Παρεκτροπή",
        "lemma_norm": norm_text("Παρεκτροπή"),
        "lemma_sort": norm_text("Παρεκτροπή"),
        "entry_raw": "Παρεκτροπή, deflexio, col. 224 D. Παρεκτροπή τῆς θείας δοῦ.",
        "context_raw": None,
        "heading_letter": "Π",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-118.txt"),
        "confidence": 1.00,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_016",
            "selected_target_file_reason": "helper best candidate resolves the col. 224 D citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 224 D",
                "page_ref_raw": "col. 224 D",
                "page_ref_int": 224,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-118.txt"),
                "target_file_probability": 0.999592,
                "confidence": 1.00,
                "raw_json": {
                    "helper_entry_id": "pg027_016",
                    "source_token": "col. 224 D",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0019",
        "entry_id": "pg027_019",
        "entry_order": 19,
        "entry_kind": "lemma",
        "lemma_raw": "Πολυμερής",
        "lemma_display": "Πολυμερής",
        "lemma_norm": norm_text("Πολυμερής"),
        "lemma_sort": norm_text("Πολυμερής"),
        "entry_raw": "Πολυμερής, verto, diuturnam curam habere ( psal. cxxxi). Alias ejus voces significationes vide in Lexicis.",
        "context_raw": None,
        "heading_letter": "Π",
        "inferred_printed_page": 1410,
        "target_file_best": section_start_file,
        "confidence": 0.93,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "note": "scripture citation only; the following line is a remission entry.",
        },
    },
    {
        "entry_key": f"{section_key}:entry:0020",
        "entry_id": "pg027_020",
        "entry_order": 20,
        "entry_kind": "cross_reference",
        "lemma_raw": "Πολυωρία",
        "lemma_display": "Πολυωρία",
        "lemma_norm": norm_text("Πολυωρία"),
        "lemma_sort": norm_text("Πολυωρία"),
        "entry_raw": "Πολυωρία, ibid. Πολυωρία τὴν πολύχρ- νότητά φησιν, id est, diuturnitatem, malo, diu- turnam sollicitudinem.",
        "context_raw": None,
        "heading_letter": "Π",
        "inferred_printed_page": 1410,
        "target_file_best": section_start_file,
        "confidence": 0.60,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "note": "cross-reference / remission with ibid.; no fresh material locator.",
        },
    },
    {
        "entry_key": f"{section_key}:entry:0021",
        "entry_id": "pg027_021",
        "entry_order": 21,
        "entry_kind": "lemma",
        "lemma_raw": "Πολυχρονία",
        "lemma_display": "Πολυχρονία",
        "lemma_norm": norm_text("Πολυχρονία"),
        "lemma_sort": norm_text("Πολυχρονία"),
        "entry_raw": "Πολυχρονία, id est, πολυ- χρονότης, temporis diuturnitas, col. 96 B.",
        "context_raw": None,
        "heading_letter": "Π",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-054.txt"),
        "confidence": 0.91,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_017",
            "selected_target_file_reason": "helper best candidate resolves the col. 96 B citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 96 B",
                "page_ref_raw": "col. 96 B",
                "page_ref_int": 96,
                "page_ref_col": "B",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-054.txt"),
                "target_file_probability": 0.999959,
                "confidence": 0.91,
                "raw_json": {
                    "helper_entry_id": "pg027_017",
                    "source_token": "col. 96 B",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0022",
        "entry_id": "pg027_022",
        "entry_order": 22,
        "entry_kind": "lemma",
        "lemma_raw": "Προλήψι",
        "lemma_display": "Προλήψι",
        "lemma_norm": norm_text("Προλήψι"),
        "lemma_sort": norm_text("Προλήψι"),
        "entry_raw": "Προλήψι, q. d. praeorcular, col. 80 D.",
        "context_raw": None,
        "heading_letter": "Π",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-054.txt"),
        "confidence": 0.80,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_018",
            "selected_target_file_reason": "helper best candidate resolves the col. 80 D citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 80 D",
                "page_ref_raw": "col. 80 D",
                "page_ref_int": 80,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-054.txt"),
                "target_file_probability": 0.802533,
                "confidence": 0.80,
                "raw_json": {
                    "helper_entry_id": "pg027_018",
                    "source_token": "col. 80 D",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0023",
        "entry_id": "pg027_023",
        "entry_order": 23,
        "entry_kind": "lemma",
        "lemma_raw": "Σαρκείος",
        "lemma_display": "Σαρκείος",
        "lemma_norm": norm_text("Σαρκείος"),
        "lemma_sort": norm_text("Σαρκείος"),
        "entry_raw": "Σαρκείος, qui carnem gessit, dictum de Christo, col. 1408 A.",
        "context_raw": None,
        "heading_letter": "Σ",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "d522e5b8-afda-421a-bba0-e241fb78d7b5-712.txt"),
        "confidence": 0.94,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_019",
            "selected_target_file_reason": "helper's top candidate was the index page itself; the body spread with printed page 1408 is file 712.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 1408 A",
                "page_ref_raw": "col. 1408 A",
                "page_ref_int": 1408,
                "page_ref_col": "A",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "d522e5b8-afda-421a-bba0-e241fb78d7b5-712.txt"),
                "target_file_probability": 0.94,
                "confidence": 0.94,
                "raw_json": {
                    "helper_entry_id": "pg027_019",
                    "source_token": "col. 1408 A",
                    "helper_best_candidate": "index_page_candidate was rejected in favor of the body spread containing printed page 1408.",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0024",
        "entry_id": "pg027_024",
        "entry_order": 24,
        "entry_kind": "lemma",
        "lemma_raw": "Σταχὺ",
        "lemma_display": "Σταχὺ",
        "lemma_norm": norm_text("Σταχὺ"),
        "lemma_sort": norm_text("Σταχὺ"),
        "entry_raw": "Σταχὺ: Ἐστιν ἡ σταχὺ σμύρνης εἶδος λεπτότατον. Ἐκλείθεντος γὰρ τοῦ ἄρωματος, ὅσον μεν γὰρ αὐ- τοῦ ῥύθμον εἰς σταχὺ ἀπομερίζεται, τὸ δὲ παχύτε- ρον ἀπομένον σμύρνα παροξυστίζεται, col. 212 A.",
        "context_raw": None,
        "heading_letter": "Σ",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-112.txt"),
        "confidence": 0.92,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_020",
            "selected_target_file_reason": "helper best candidate resolves the col. 212 A citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 212 A",
                "page_ref_raw": "col. 212 A",
                "page_ref_int": 212,
                "page_ref_col": "A",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-112.txt"),
                "target_file_probability": 0.91807,
                "confidence": 0.92,
                "raw_json": {
                    "helper_entry_id": "pg027_020",
                    "source_token": "col. 212 A",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0025",
        "entry_id": "pg027_025",
        "entry_order": 25,
        "entry_kind": "lemma",
        "lemma_raw": "Τόμος",
        "lemma_display": "Τόμος",
        "lemma_norm": norm_text("Τόμος"),
        "lemma_sort": norm_text("Τόμος"),
        "entry_raw": "Τόμος, rescriptum compendiosum, sic vocatum quod in eo res συνετετηγμένας tracterunt. Κεφα- λάδα α' Ἐβραίων τὸν τόμον φασιν, col. 192 D.",
        "context_raw": None,
        "heading_letter": "Τ",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-102.txt"),
        "confidence": 0.99,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_021",
            "selected_target_file_reason": "helper best candidate resolves the col. 192 D citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 192 D",
                "page_ref_raw": "col. 192 D",
                "page_ref_int": 192,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "9b9d2f1e-d72f-4217-ad82-075cbb8e3b48-102.txt"),
                "target_file_probability": 0.990273,
                "confidence": 0.99,
                "raw_json": {
                    "helper_entry_id": "pg027_021",
                    "source_token": "col. 192 D",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0026",
        "entry_id": "pg027_026",
        "entry_order": 26,
        "entry_kind": "lemma",
        "lemma_raw": "Ῥινακή",
        "lemma_display": "Ῥινακή",
        "lemma_norm": norm_text("Ῥινακή"),
        "lemma_sort": norm_text("Ῥινακή"),
        "entry_raw": "Ῥινακή. Sic vocantur plurimi psalmi, quia nunc- rum ita canebantur, ut diaconus primam versi- culi partem proferret, et populus quasi respon- dendo, postremam absolveret, nam ὑπακούοι ἄν ὑπακού- οι, id est, respondere, col. 37 B.",
        "context_raw": None,
        "heading_letter": "Ρ",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-025.txt"),
        "confidence": 0.67,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_022",
            "selected_target_file_reason": "helper best candidate resolves the col. 37 B citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 37 B",
                "page_ref_raw": "col. 37 B",
                "page_ref_int": 37,
                "page_ref_col": "B",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-025.txt"),
                "target_file_probability": 0.669949,
                "confidence": 0.67,
                "raw_json": {
                    "helper_entry_id": "pg027_022",
                    "source_token": "col. 37 B",
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0027",
        "entry_id": "pg027_027",
        "entry_order": 27,
        "entry_kind": "sublemma",
        "lemma_raw": "Ῥινακή",
        "lemma_display": "Ῥινακή",
        "lemma_norm": norm_text("Ῥινακή"),
        "lemma_sort": norm_text("Ῥινακή"),
        "entry_raw": "Ῥινακή, item q. d. exaudito, ea sententia dicitur, col. 469 D. Τῆς ἀγάπης μισθὸν ἐδέξατο τὴν ὑπ- ακοήν, id est, in dilectionis præmium exaudivit il- lum Deus.",
        "context_raw": None,
        "heading_letter": "Ρ",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-241.txt"),
        "confidence": 0.55,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_022",
            "selected_target_file_reason": "the second printed locator was resolved by the rank-4 target candidate and corroborated by local OCR inspection.",
            "locator_note": "second sense under the same headword; split from the preceding Ῥινακή line to keep the locators separate.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 469 D",
                "page_ref_raw": "col. 469 D",
                "page_ref_int": 469,
                "page_ref_col": "D",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-241.txt"),
                "target_file_probability": 0.037649,
                "confidence": 0.55,
                "raw_json": {
                    "helper_entry_id": "pg027_022",
                    "source_token": "col. 469 D",
                    "helper_rank": 4,
                },
            }
        ],
    },
    {
        "entry_key": f"{section_key}:entry:0028",
        "entry_id": "pg027_028",
        "entry_order": 28,
        "entry_kind": "lemma",
        "lemma_raw": "Ῥιναλαῖος",
        "lemma_display": "Ῥιναλαῖος",
        "lemma_norm": norm_text("Ῥιναλαῖος"),
        "lemma_sort": norm_text("Ῥιναλαῖος"),
        "entry_raw": "Ῥιναλαῖος, idem videtur significare 'quod ὑπ- ακούειν, id est respondendo cantare, ut fiebat olim cum diaconus priorem versiculum, populus autem posteriorem partem canebat, col. 256 B.",
        "context_raw": None,
        "heading_letter": "Ρ",
        "inferred_printed_page": 1410,
        "target_file_best": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-125.txt"),
        "confidence": 0.73,
        "raw_json": {
            "section_kind": "foreign_terms",
            "section_kind_reason": "Greek alphabetical index of terms and locutions.",
            "helper_entry_id": "pg027_023",
            "selected_target_file_reason": "helper best candidate resolves the col. 256 B citation.",
        },
        "refs": [
            {
                "ref_order": 1,
                "ref_kind": "editorial_page_column",
                "ref_raw": "col. 256 B",
                "page_ref_raw": "col. 256 B",
                "page_ref_int": 256,
                "page_ref_col": "B",
                "line_ref_raw": None,
                "range_start_raw": None,
                "range_end_raw": None,
                "target_file": str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-125.txt"),
                "target_file_probability": 0.734671,
                "confidence": 0.73,
                "raw_json": {
                    "helper_entry_id": "pg027_023",
                    "source_token": "col. 256 B",
                },
            }
        ],
    },
]


def make_entry(entry_spec: dict) -> dict:
    entry = {
        "entry_key": entry_spec["entry_key"],
        "section_key": section_key,
        "parent_node_key": None,
        "entry_order": entry_spec["entry_order"],
        "entry_kind": entry_spec["entry_kind"],
        "lemma_raw": entry_spec["lemma_raw"],
        "lemma_display": entry_spec["lemma_display"],
        "lemma_norm": entry_spec["lemma_norm"],
        "lemma_sort": entry_spec["lemma_sort"],
        "entry_raw": entry_spec["entry_raw"],
        "context_raw": entry_spec["context_raw"],
        "heading_letter": entry_spec["heading_letter"],
        "inferred_printed_page": entry_spec["inferred_printed_page"],
        "section_start_file": section_start_file,
        "editorial_anchor_file": section_start_file,
        "target_file_best": entry_spec["target_file_best"],
        "confidence": entry_spec["confidence"],
        "raw_json": dict(entry_spec["raw_json"], helper=helper_summary(helper_map, entry_spec["entry_id"]))
        if helper_summary(helper_map, entry_spec["entry_id"])
        else dict(entry_spec["raw_json"]),
    }
    return entry


def make_refs(entry_spec: dict) -> list[dict]:
    refs = []
    for ref_spec in entry_spec.get("refs", []):
        refs.append(
            {
                "entry_key": entry_spec["entry_key"],
                "ref_order": ref_spec["ref_order"],
                "ref_kind": ref_spec["ref_kind"],
                "ref_raw": ref_spec["ref_raw"],
                "page_ref_raw": ref_spec["page_ref_raw"],
                "page_ref_int": ref_spec["page_ref_int"],
                "page_ref_col": ref_spec["page_ref_col"],
                "line_ref_raw": ref_spec["line_ref_raw"],
                "range_start_raw": ref_spec["range_start_raw"],
                "range_end_raw": ref_spec["range_end_raw"],
                "target_file": ref_spec["target_file"],
                "target_file_probability": ref_spec["target_file_probability"],
                "section_start_file": section_start_file,
                "editorial_anchor_file": section_start_file,
                "confidence": ref_spec["confidence"],
                "raw_json": ref_spec["raw_json"],
            }
        )
    return refs


def make_scripture_refs(entry_key: str, refs: list[dict]) -> list[dict]:
    out = []
    for idx, sr in enumerate(refs, start=1):
        out.append(
            {
                "entry_key": entry_key,
                "ref_order": idx,
                "ref_role": "citation",
                "ref_raw": sr["ref_raw"],
                "book_raw": sr["book_raw"],
                "book_norm": sr["book_norm"],
                "chapter_start": sr["chapter_start"],
                "verse_start": sr["verse_start"],
                "chapter_end": sr["chapter_end"],
                "verse_end": sr["verse_end"],
                "is_range": sr["is_range"],
                "confidence": sr["confidence"],
                "raw_json": sr["raw_json"],
            }
        )
    return out


entries = [make_entry(spec) for spec in entries_spec]
refs = []
scripture_refs = []

for spec in entries_spec:
    refs.extend(make_refs(spec))

scripture_refs.extend(
    make_scripture_refs(
        f"{section_key}:entry:0007",
        [
            {
                "ref_raw": "psal. cxxxviii.",
                "book_raw": "psal.",
                "book_norm": "Salmos",
                "chapter_start": 138,
                "verse_start": None,
                "chapter_end": 138,
                "verse_end": None,
                "is_range": False,
                "confidence": 0.94,
                "raw_json": {"source_token": "psal. cxxxviii.", "note": "explicit Psalm citation"},
            }
        ],
    )
)
scripture_refs.extend(
    make_scripture_refs(
        f"{section_key}:entry:0009",
        [
            {
                "ref_raw": "psal. cxxxiv.",
                "book_raw": "psal.",
                "book_norm": "Salmos",
                "chapter_start": 134,
                "verse_start": None,
                "chapter_end": 134,
                "verse_end": None,
                "is_range": False,
                "confidence": 0.94,
                "raw_json": {"source_token": "psal. cxxxiv.", "note": "explicit Psalm citation"},
            }
        ],
    )
)
scripture_refs.extend(
    make_scripture_refs(
        f"{section_key}:entry:0019",
        [
            {
                "ref_raw": "psal. cxxxi.",
                "book_raw": "psal.",
                "book_norm": "Salmos",
                "chapter_start": 131,
                "verse_start": None,
                "chapter_end": 131,
                "verse_end": None,
                "is_range": False,
                "confidence": 0.95,
                "raw_json": {"source_token": "psal. cxxxi.", "note": "explicit Psalm citation"},
            }
        ],
    )
)

nodes = [
    {
        "node_key": f"{section_key}:node:001:A",
        "section_key": section_key,
        "parent_node_key": None,
        "node_order": 1,
        "node_kind": "letter_group",
        "label_raw": "A",
        "label_norm": "a",
        "label_sort": "a",
        "node_level": 1,
        "confidence": 0.99,
        "raw_json": {"source_token": "A"},
    },
    {
        "node_key": f"{section_key}:node:002:Δ",
        "section_key": section_key,
        "parent_node_key": None,
        "node_order": 2,
        "node_kind": "letter_group",
        "label_raw": "Δ",
        "label_norm": "δ",
        "label_sort": "δ",
        "node_level": 1,
        "confidence": 0.99,
        "raw_json": {"source_token": "Δ"},
    },
    {
        "node_key": f"{section_key}:node:003:M",
        "section_key": section_key,
        "parent_node_key": None,
        "node_order": 3,
        "node_kind": "letter_group",
        "label_raw": "M",
        "label_norm": "m",
        "label_sort": "m",
        "node_level": 1,
        "confidence": 0.99,
        "raw_json": {"source_token": "M"},
    },
    {
        "node_key": f"{section_key}:node:004:Π",
        "section_key": section_key,
        "parent_node_key": None,
        "node_order": 4,
        "node_kind": "letter_group",
        "label_raw": "Π",
        "label_norm": "π",
        "label_sort": "π",
        "node_level": 1,
        "confidence": 0.99,
        "raw_json": {"source_token": "Π"},
    },
    {
        "node_key": f"{section_key}:node:005:Σ",
        "section_key": section_key,
        "parent_node_key": None,
        "node_order": 5,
        "node_kind": "letter_group",
        "label_raw": "Σ",
        "label_norm": "σ",
        "label_sort": "σ",
        "node_level": 1,
        "confidence": 0.99,
        "raw_json": {"source_token": "Σ"},
    },
    {
        "node_key": f"{section_key}:node:006:Τ",
        "section_key": section_key,
        "parent_node_key": None,
        "node_order": 6,
        "node_kind": "letter_group",
        "label_raw": "Τ",
        "label_norm": "τ",
        "label_sort": "τ",
        "node_level": 1,
        "confidence": 0.99,
        "raw_json": {"source_token": "Τ"},
    },
    {
        "node_key": f"{section_key}:node:007:Ρ",
        "section_key": section_key,
        "parent_node_key": None,
        "node_order": 7,
        "node_kind": "letter_group",
        "label_raw": "Ρ",
        "label_norm": "ρ",
        "label_sort": "ρ",
        "node_level": 1,
        "confidence": 0.99,
        "raw_json": {"source_token": "Ρ"},
    },
]


payload = {
    "schema_version": 1,
    "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
    "volume": {
        "volume_id": "PG027",
        "collection": "PG",
        "source_root": str(SOURCE_ROOT),
        "volume_label": "Patrologia Graeca 27",
    },
    "sections": [
        {
            "section_key": section_key,
            "volume_id": "PG027",
            "work_key": None,
            "section_order": 1,
            "section_kind": "foreign_terms",
            "heading_raw": "INDEX GRÆCITATIS.",
            "heading_norm": "index graecitatis",
            "heading_letter": None,
            "page_start": 1410,
            "page_end": 1410,
            "file_start": section_start_file,
            "file_end": section_start_file,
            "confidence": 0.99,
            "raw_json": {
                "section_kind": "foreign_terms",
                "section_kind_reason": "Greek alphabetical index of terms and locutions.",
                "evidence_files": [section_start_file],
            },
        }
    ],
    "nodes": nodes,
    "entries": entries,
    "refs": refs,
    "scripture_refs": scripture_refs,
    "coverage": {
        "entries_status": "partial_recovery",
        "entries_status_reason": "Recovered the full visible INDEX GRÆCITATIS page conservatively. One lemma is OCR-corrupted (Olxoxumla -> Οἰκονομία by context), one headword is split into a remission entry (Πολυωρία), and the two Ῥινακή senses were separated so their locators remain distinct.",
        "evidence_files": [
            section_start_file,
            str(SOURCE_ROOT / "553552b0-d0e2-43e2-a082-cdb5d460b3d4-052.txt"),
            str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-277.txt"),
            str(SOURCE_ROOT / "818a96fc-b772-475c-9793-9fdbd5aaa31d-122.txt"),
            str(SOURCE_ROOT / "205f7cab-85fb-43c9-bba4-314003473964-241.txt"),
        ],
    },
    "notes": [
        "PAGE 713 is the only index page; the printed heading carries the index title and the closing TOC on page 714 confirms the section order.",
        "Helper evidence is preserved in raw_json but not allowed to override the OCR page evidence when the helper preferred the index page itself.",
        "Scripture-only glosses are serialized as scripture_refs and not forced into material refs.",
    ],
}


OUTPUT_FILE.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")

